trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  azure_subscription: 'Azure subscription 1(5fa73faf-6a16-4e4e-a3c0-a3f4f7415956)'
  working_dir : '$(System.DefaultWorkingDirectory)/Terraform'

stages:
  - stage: DeleteAppService
    displayName: 'Deleting Infrastructure'
    jobs:
      - job: TerraformStage
        displayName: 'Terraform Stage'
        steps:
          - task: TerraformInstaller@1
            displayName: 'Terraform install'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: 'Terraform init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(working_dir)'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: '$(azure_subscription)'
              backendAzureRmResourceGroupName: 'Statefiles'
              backendAzureRmStorageAccountName: 'statefilesp3'
              backendAzureRmContainerName: 'tfstates'
              backendAzureRmKey: 'statefile.tfstate'

          - task: TerraformTask@5
            displayName: 'Terraform destroy'
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(working_dir)'
              commandOptions: '--auto-approve'
              environmentServiceNameAzureRM: '$(azure_subscription)'